SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SelectEverything9]
AS
BEGIN
    SET NOCOUNT ON;
	DECLARE @Number1 INT = 2, @Number2 INT = 3

    SELECT @Number1 * @Number2 FROM dbo.NewspaperReader AS NR;

END;
GO
