CREATE TABLE [dbo].[GenericOrClassWord]
(
[GenericOrClassWordId] [int] NOT NULL IDENTITY(1, 1),
[Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Code] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Time] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Key] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Value] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Term] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Class] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Style] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Segment] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Default] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Deleted] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Active] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inactive] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Permission] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Locked] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Total] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Quantity] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Weight] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Percent] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cost] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Price] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Balance] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Average] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Discount] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Limit] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Due] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fee] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fine] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Stamp] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Flag] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Slug] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Level] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[URL] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subject] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Body] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Alias] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Format] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Group] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GenericOrClassWord] ADD CONSTRAINT [PK_GenericOrClassWord] PRIMARY KEY CLUSTERED ([GenericOrClassWordId]) ON [PRIMARY]
GO
