CREATE TABLE [dbo].[UNIQUEIDENTIFIERClusteredIndex]
(
[GUID] [uniqueidentifier] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[UNIQUEIDENTIFIERClusteredIndex] ADD CONSTRAINT [PK_UNIQUEIDENTIFIERClusteredIndex] PRIMARY KEY CLUSTERED  ([GUID]) ON [PRIMARY]
GO
